<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>SR_Ch04_notes</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="SR_Ch04_notes_files/libs/clipboard/clipboard.min.js"></script>
<script src="SR_Ch04_notes_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="SR_Ch04_notes_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="SR_Ch04_notes_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="SR_Ch04_notes_files/libs/quarto-html/popper.min.js"></script>
<script src="SR_Ch04_notes_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SR_Ch04_notes_files/libs/quarto-html/anchor.min.js"></script>
<link href="SR_Ch04_notes_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SR_Ch04_notes_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SR_Ch04_notes_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SR_Ch04_notes_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SR_Ch04_notes_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">SR_Ch04_notes</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="geocentric-models-notes" class="level1">
<h1>Geocentric Models Notes</h1>
<p>Why normal?</p>
<ol type="1">
<li>generative: summed fluctuations tend toward normal distribution</li>
<li>inferential: for estimating mean and variance, normal distribution is least informative distribution (max entropy → fewest assumptions)</li>
</ol>
<p>Ptolemy is often ridiculed for his geocentric model of the solar system, but he was mathematically brilliant. He computed an accurate model of the motions of the planets (<em>epicycles</em> - accurate from the earthly perspective, would just have to be re-calibrated every 100 years). Makes useful predictions given narrow domain of questioning. = Generalized system of approximation (Fourier series).</p>
<p>Linear regression is the geometric model of applied statistics. Linear regression: family of simple golems attempting to learn about the mean and variance of some measurement using an additive combinations of other measurements</p>
<section id="linear-regression-as-a-bayesian-procedure" class="level3">
<h3 class="anchored" data-anchor-id="linear-regression-as-a-bayesian-procedure">Linear regression as a Bayesian procedure</h3>
<p>Which uses a <strong>Gaussian (normal) distribution</strong> to describe our golem’s uncertainty about some measurement of interest.</p>
<p><strong>Binomial distribution</strong> models the number of <em>discrete</em> successes (k) in a fixed number (n) of independent binary trials (Y/N, T/F). As the number of trials becomes large, the binomial distribution approaches the <em>continuous</em> Gaussian distribution, which is characterized by a bell-shaped curve defined by its mean and SD.</p>
<section id="normal-by-addition" class="level4">
<h4 class="anchored" data-anchor-id="normal-by-addition">Normal by addition</h4>
<p>Random walks on a soccer field.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pos <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="dv">1000</span>,<span class="fu">sum</span>(<span class="fu">runif</span>(<span class="dv">16</span>,<span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span>)))</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(pos))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>INC number of steps INC stabilization on the Gaussian distribution. Any process that adds together random values from the same distribution converges to normal. Fluctuations from the mean cancel themselves out - most likely sum is sum in which every fluctuation is canceled by another (sum of zero)</p>
<ul>
<li>Regardless of underlying distribution</li>
</ul>
</section>
<section id="normal-by-multiplication" class="level4">
<h4 class="anchored" data-anchor-id="normal-by-multiplication">Normal by multiplication</h4>
<p>Another way to get normal distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">prod</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">0</span>,<span class="fl">0.1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.120871</code></pre>
</div>
</div>
<ul>
<li>Samples 12 random numbers between 1.0 and 1.1, each representing a proportional increase in growth. The product of all 12 is computed and returned.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>growth <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="fl">1e4</span>, <span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">0</span>,<span class="fl">0.1</span>)))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(growth, <span class="at">norm.comp=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The effect at each locus was multiplied by the effects at all the others, NOT ADDED. Normal distribution because the effect at each locus is SMALL (multiplying small numbers is approx same as addition).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Small effects that multiply together are approximately additive, so they tend to stabilize on Gaussian distributions</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>big <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="fl">1e4</span>, <span class="fu">prod</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">0</span>,<span class="fl">0.5</span>)))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>small <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="fl">1e4</span>, <span class="fu">prod</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">0</span>,<span class="fl">0.01</span>)))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(big, <span class="at">norm.comp=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(small, <span class="at">norm.comp=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="normal-by-log-multiplication" class="level4">
<h4 class="anchored" data-anchor-id="normal-by-log-multiplication">Normal by log-multiplication</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>log.big <span class="ot">&lt;-</span> <span class="fu">replicate</span>(<span class="fl">1e4</span>, <span class="fu">log</span>(<span class="fu">prod</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">runif</span>(<span class="dv">12</span>,<span class="dv">0</span>,<span class="fl">0.5</span>))))</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(log.big, <span class="at">norm.comp=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Adding logs is equivalent to multiplying the original numbers. Measurement scales are arbitrary, and it’s natural to measure sound, earthquakes, information on a log scale.</p>
</section>
</section>
<section id="using-gaussian-distributions" class="level3">
<h3 class="anchored" data-anchor-id="using-gaussian-distributions">Using Gaussian distributions</h3>
<p><strong>Ontological reason:</strong> World full of Gaussian distributions: measurement errors, variations in growth, velocities of molecules.<br>
Processes that add together fluctuations.</p>
<ul>
<li>Member of <strong>exponential family</strong> of natural distributions</li>
</ul>
<p><strong>Epistemological reason:</strong> Maximum entropy → minimal assumptions about the data (just that the measure has finite variance)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>( <span class="fu">exp</span>( <span class="sc">-</span>x<span class="sc">^</span><span class="dv">2</span> ) , <span class="at">from=</span><span class="sc">-</span><span class="dv">3</span> , <span class="at">to=</span><span class="dv">3</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Gaussian is <em>continuous</em> - value <span class="math inline">\(y\)</span> can be any continuous value. In contrast to binomial, which requires integers.</p>
<ul>
<li><p>Probability mass functions: discrete outcomes (like binomial) → denoted <span class="math inline">\(Pr\)</span></p>
<ul>
<li>Cannot be greater than 1</li>
</ul></li>
<li><p>Probability density functions: continuous outcomes → denoted <span class="math inline">\(P\)</span> or <span class="math inline">\(f\)</span> .</p>
<ul>
<li><p>can be greater than 1</p>
<ul>
<li><p>Probability density is the rate of change in cumulative probability</p></li>
<li><p>Area under the density function will never exceed 1 = probability mass</p></li>
</ul></li>
</ul></li>
</ul>
</section>
<section id="a-language-for-describing-models" class="level2">
<h2 class="anchored" data-anchor-id="a-language-for-describing-models">A language for describing models</h2>
<div class="callout callout-style-simple callout-tip no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Recipe for statistical models
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Recognize set of variables we want to understand. Data are observable variables. Parameters are unobservable, like rates and averages.</li>
<li>For each variable, define it either in terms of other variables or a probability distribution</li>
<li>Combination of variables and their probability distributions defines a <em>joint generative model</em> that can be used both to simulate hypothetical observations as well as analyze real ones.</li>
</ol>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Summarizing the model
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(y_{i}\)</span> ~ <span class="math inline">\(Normal(µ_{i}, σ)\)</span></p>
<p><span class="math inline">\(µ{i} = 𝛽x{i}\)</span></p>
<p><span class="math inline">\(𝛽\)</span> ~ <span class="math inline">\(Normal(0,10)\)</span></p>
<p><span class="math inline">\(σ\)</span> ~ <span class="math inline">\(Exponential(1)\)</span></p>
<p><span class="math inline">\(x_{i}\)</span> ~ <span class="math inline">\(Normal(0,1)\)</span></p>
</div>
</div>
<p>Revising the globe-tossing model:</p>
<p><span class="math display">\[
W \sim {\sf Binom}(N, p)
\]</span></p>
<p><span class="math display">\[
p \sim {\sf Uniform}(0,1)
\]</span></p>
<ul>
<li><p><u>Likelihood function used in Bayes’ thm</u>: The count <span class="math inline">\(W\)</span> is distributed binomially with sample size N and probability <span class="math inline">\(p\)</span></p></li>
<li><p><u>Define priors</u>: The prior for <span class="math inline">\(p\)</span> is assumed to be uniform between 0 and 1</p></li>
</ul>
<p><strong>Stochastic</strong>: indicated by ~ symbol. No single instance of the variable on left is known with certainty, but is instead characterized by a probabilistic mapping</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>w <span class="ot">&lt;-</span> <span class="dv">6</span>; n <span class="ot">&lt;-</span> <span class="dv">9</span>;</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>p_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="at">length.out=</span><span class="dv">100</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> <span class="fu">dbinom</span>(w,n,p_grid) <span class="sc">*</span> <span class="fu">dunif</span>(p_grid,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>posterior <span class="ot">&lt;-</span> posterior<span class="sc">/</span><span class="fu">sum</span>(posterior)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="gaussian-model-of-height" class="level2">
<h2 class="anchored" data-anchor-id="gaussian-model-of-height">Gaussian Model of height</h2>
<p>Loaded the data, not place them into convenient object</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> Howell1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong>Data frame</strong> simply named <code>d</code>: special kind of <code>list</code> in R, table with named columns, correponding with variables, and numbered rows, corresponding to individual cases</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># str() compactly display the structure of an R object </span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(d)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   544 obs. of  4 variables:
 $ height: num  152 140 137 157 145 ...
 $ weight: num  47.8 36.5 31.9 53 41.3 ...
 $ age   : num  63 63 65 41 51 35 32 27 19 54 ...
 $ male  : int  1 0 0 1 0 1 0 1 0 1 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># precis() helpful for summarizing posterior distr further on </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(d)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>              mean         sd      5.5%     94.5%     histogram
height 138.2635963 27.6024476 81.108550 165.73500 ▁▁▁▁▁▁▁▂▁▇▇▅▁
weight  35.6106176 14.7191782  9.360721  54.50289 ▁▂▃▂▂▂▂▅▇▇▃▂▁
age     29.3443934 20.7468882  1.000000  66.13500     ▇▅▅▃▅▂▂▁▁
male     0.4724265  0.4996986  0.000000   1.00000    ▇▁▁▁▁▁▁▁▁▇</code></pre>
</div>
</div>
<p>Working with columns</p>
<ul>
<li><code>$</code> → extract the column named <code>height</code> from the data frame <code>d</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>height</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d[d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span>,]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li>Index notation: <code>[row, column]</code></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(d2<span class="sc">$</span>height)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Height raw data looks approx Gaussian, BUT not a good idea to gawk at raw data and decide how to model them</li>
</ul>
<p>Write general model and compute plausibility of each µ and σ. To define the heights as normally distributed with a mean µ and sd σ:</p>
<p><span class="math display">\[
h_{i} \sim {Normal}(µ,σ)
\]</span></p>
<ul>
<li><p>h → list of heights</p></li>
<li><p>subscript i –&gt; each individual element of list, takes on row numbers (1-32, no. heights in <code>d2$height</code> )</p></li>
</ul>
<p>All the golem knows about each height measurement is defined by the name normal distribution with mean µ and standard dev σ. The model assumes that the values <span class="math inline">\(h_{i}\)</span> are <strong>independent and identically distributed (IDD)</strong>. In other words, each value of h has the same probability function, independent of the other h values and using the same parameters. But hardly true - heights within families are correlated.</p>
<section id="priors" class="level4">
<h4 class="anchored" data-anchor-id="priors">Priors</h4>
<p>The parameters to be estimated are µ and σ → so need prior <span class="math inline">\(Pr(µ, σ)\)</span> or the joint prior probability for all parameters. Assume that they’re independent of each other or <span class="math inline">\(Pr(µ, σ) = Pr(µ)Pr(σ)\)</span></p>
<p><span class="math display">\[
h_{i} \sim {Normal}(µ,σ)
\]</span></p>
<p><span class="math display">\[
µ \sim{Normal}(178, 20)
\]</span></p>
<p><span class="math display">\[
σ \sim {Uniform}(0, 50)
\]</span></p>
<p>The prior for µ is a broad Gaussian prior, centered on 178cm, with 95% of probability between 178 ±40.</p>
<ul>
<li>Why 178 cm? Author is 178 cm tall. And the range from 138 cm to 218 cm encompasses a huge range of plausible mean heights for human populations. So domain-specific information has gone into this prior. Everyone knows something about human height and can set a reasonable and vague prior of this kind.</li>
</ul>
<p>Whatever the prior, it’s a very good idea to <strong>plot your priors</strong>, so you have a sense of the assumption they build into the model.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x,<span class="dv">178</span>,<span class="dv">20</span>), <span class="at">from=</span><span class="dv">100</span>, <span class="at">to=</span><span class="dv">250</span>, <span class="at">xlab =</span> <span class="st">"mu"</span>,<span class="at">ylab=</span><span class="st">"density"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>the golem is assuming that the average height (not each individual height) is almost certainly between 140 cm and 220 cm.</li>
</ul>
<p>The σ prior is a truly flat prior, a uniform one, that functions just to constrain σ to have positive probability between zero and 50cm. View it with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dunif</span>(x,<span class="dv">0</span>,<span class="dv">50</span>), <span class="at">from=</span><span class="sc">-</span><span class="dv">10</span>, <span class="at">to=</span><span class="dv">60</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="prior-predictive-simulation" class="level4">
<h4 class="anchored" data-anchor-id="prior-predictive-simulation">Prior predictive simulation</h4>
<ul>
<li><p>See what your priors imply about the distribution of heights</p></li>
<li><p>Helps diagnose bad choices</p></li>
<li><p>Simulate heights by sampling from the prior</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sample_mu <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fl">1e4</span>, <span class="dv">178</span>,<span class="dv">20</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>sample_sigma <span class="ot">&lt;-</span> <span class="fu">runif</span>(<span class="fl">1e4</span>,<span class="dv">0</span>,<span class="dv">50</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>prior_h <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fl">1e4</span>, sample_mu, sample_sigma)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(prior_h, <span class="at">xlab=</span><span class="st">"height"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Expected distribution of heights, averaged over the prior</p></li>
<li><p>Prior prob distribution is not itself Gaussian - not an empirical expectation but a distribution of relative plausibilities of different heights, BEFORE seeing the data</p></li>
</ul>
<p>Compare to a less informative prior for average height µ ~ Normal(178,100). Priors with large SDs are common in Bayesian models, but not really sensible.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>sample_mu <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fl">1e4</span>, <span class="dv">178</span>,<span class="dv">100</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>prior_h <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(<span class="fl">1e4</span>, sample_mu, sample_sigma)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(prior_h)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v=</span><span class="dv">0</span>, <span class="at">lty =</span> <span class="st">"dashed"</span>) <span class="co">#plot line at x=0 to show where negative values occur</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>4% of expected heights are negative. Also expects some giants: 18% of expected heights over 272cm (tallest record)</li>
</ul>
</section>
<section id="grid-approximation-of-posterior-distribution" class="level4">
<h4 class="anchored" data-anchor-id="grid-approximation-of-posterior-distribution">Grid approximation of posterior distribution</h4>
<p>For the first time modeling Gaussian distribution, demonstrate calculations with brute force (usually impractical)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mu.list <span class="ot">&lt;-</span> <span class="fu">seq</span>( <span class="at">from=</span><span class="dv">150</span>, <span class="at">to=</span><span class="dv">160</span> , <span class="at">length.out=</span><span class="dv">100</span> )</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>sigma.list <span class="ot">&lt;-</span> <span class="fu">seq</span>( <span class="at">from=</span><span class="dv">7</span> , <span class="at">to=</span><span class="dv">9</span> , <span class="at">length.out=</span><span class="dv">100</span> )</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>( <span class="at">mu=</span>mu.list , <span class="at">sigma=</span>sigma.list )</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>LL <span class="ot">&lt;-</span> <span class="fu">sapply</span>( <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(post) , <span class="cf">function</span>(i) <span class="fu">sum</span>(</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dnorm</span>( d2<span class="sc">$</span>height , post<span class="sc">$</span>mu[i] , post<span class="sc">$</span>sigma[i] , <span class="at">log=</span><span class="cn">TRUE</span> ) ) )</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>prod <span class="ot">&lt;-</span> post<span class="sc">$</span>LL <span class="sc">+</span> <span class="fu">dnorm</span>( post<span class="sc">$</span>mu , <span class="dv">178</span> , <span class="dv">20</span> , <span class="cn">TRUE</span> ) <span class="sc">+</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dunif</span>( post<span class="sc">$</span>sigma , <span class="dv">0</span> , <span class="dv">50</span> , <span class="cn">TRUE</span> )</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>post<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="fu">exp</span>( post<span class="sc">$</span>prod <span class="sc">-</span> <span class="fu">max</span>(post<span class="sc">$</span>prod) )</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="fu">contour_xyz</span>(post<span class="sc">$</span>mu, post<span class="sc">$</span>sigma, post<span class="sc">$</span>prob)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/guts%20of%20the%20Gaussian%20golem-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">image_xyz</span>(post<span class="sc">$</span>mu, post<span class="sc">$</span>sigma, post<span class="sc">$</span>prob)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/guts%20of%20the%20Gaussian%20golem-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>inspect the posterior distribution (in <code>post$prob</code> ) with functions like <code>contour_xyz()</code> or <code>image_xyz()</code> in the <code>rethinking</code> package</li>
</ul>
</section>
<section id="sampling-from-the-posterior" class="level4">
<h4 class="anchored" data-anchor-id="sampling-from-the-posterior">Sampling from the posterior</h4>
<p>To summarize and understand the posterior distribution, like in Ch3. New thing: since 2 parameters and need to sample combos of them, we first randomly samples row numbers in <code>post</code> in proportion to values in <code>post$prob</code>. Then pull out parameter values on those randomly sampled rows.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>sample.rows <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(post), <span class="at">size=</span><span class="fl">1e4</span>, <span class="at">replace=</span><span class="cn">TRUE</span>, <span class="at">prob=</span>post<span class="sc">$</span>prob)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>sample.mu <span class="ot">&lt;-</span> post<span class="sc">$</span>mu[sample.rows]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>sample.sigma <span class="ot">&lt;-</span> post<span class="sc">$</span>sigma[sample.rows]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<ul>
<li><strong>Output</strong>: 1e4 samples, with replacement, from the posterior for height data, plotted below:</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(sample.mu, sample.sigma, <span class="at">cex=</span><span class="fl">0.5</span>, <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="fu">col.alpha</span>(rangi2,<span class="fl">0.1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><code>col.alpha()</code> makes the colors transparent → demonstrates density (overlapping samples)</p></li>
<li><p><code>cex</code> (character expansion, size of points) a numerical vector giving the amount by which plotting characters and symbols should be scaled relative to the default.</p></li>
<li><p><code>pch</code> (plot character) a vector of plotting characters or symbols</p></li>
</ul>
<p>Plot the densities of µ and σ → characterizing the shapes of the <strong><em>marginal</em></strong> <strong>posterior densities of µ and</strong> σ.</p>
<ul>
<li>Marginal: averaging over the other parameters</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(sample.mu)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(sample.sigma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.21-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(sample.mu)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      5%      94% 
153.9394 155.2525 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(sample.sigma)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      5%      94% 
7.323232 8.252525 </code></pre>
</div>
</div>
<p>Since these samples are just vectors of numbers, you can compute any statistic from them that you could from ordinary data.</p>
<p><strong>Sample size and the normality of the standard dev’s posterior:</strong> Posterior is not always so Gaussian in shape. For a Gaussian likelihood and a Gaussian prior on µ, the posterior distribution is always Gaussian as well, regardless of sample size. It is the standard deviation σ that causes problems. So if you care about σ—often people do not—you do need to be careful of abusing the quadratic approximation.</p>
<p>Posterior of σ has long right-hand tail. Variances (SDs) must be positive (more uncertainty about how big it is rather than how small it is.</p>
<p>Sample with small size of 20 heights:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>d3 <span class="ot">&lt;-</span> <span class="fu">sample</span>(d2<span class="sc">$</span>height, <span class="at">size=</span><span class="dv">20</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># repeat code from previous subsection</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>mu.list <span class="ot">&lt;-</span> <span class="fu">seq</span>( <span class="at">from=</span><span class="dv">150</span>, <span class="at">to=</span><span class="dv">170</span> , <span class="at">length.out=</span><span class="dv">200</span> )</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>sigma.list <span class="ot">&lt;-</span> <span class="fu">seq</span>( <span class="at">from=</span><span class="dv">4</span> , <span class="at">to=</span><span class="dv">20</span> , <span class="at">length.out=</span><span class="dv">200</span> )</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>post2 <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>( <span class="at">mu=</span>mu.list , <span class="at">sigma=</span>sigma.list )</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>post2<span class="sc">$</span>LL <span class="ot">&lt;-</span> <span class="fu">sapply</span>( <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(post2) , <span class="cf">function</span>(i)</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>( <span class="fu">dnorm</span>( d3 , <span class="at">mean=</span>post2<span class="sc">$</span>mu[i] , <span class="at">sd=</span>post2<span class="sc">$</span>sigma[i],<span class="at">log=</span><span class="cn">TRUE</span> ) ) )</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>post2<span class="sc">$</span>prod <span class="ot">&lt;-</span> post2<span class="sc">$</span>LL <span class="sc">+</span> <span class="fu">dnorm</span>( post2<span class="sc">$</span>mu , <span class="dv">178</span> , <span class="dv">20</span> , <span class="cn">TRUE</span> ) <span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="fu">dunif</span>( post2<span class="sc">$</span>sigma , <span class="dv">0</span> , <span class="dv">50</span> , <span class="cn">TRUE</span> )</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>post2<span class="sc">$</span>prob <span class="ot">&lt;-</span> <span class="fu">exp</span>( post2<span class="sc">$</span>prod <span class="sc">-</span> <span class="fu">max</span>(post2<span class="sc">$</span>prod) )</span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>sample2.rows <span class="ot">&lt;-</span> <span class="fu">sample</span>( <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(post2) , <span class="at">size=</span><span class="fl">1e4</span> , <span class="at">replace=</span><span class="cn">TRUE</span> ,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a><span class="at">prob=</span>post2<span class="sc">$</span>prob )</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>sample2.mu <span class="ot">&lt;-</span> post2<span class="sc">$</span>mu[ sample2.rows ]</span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>sample2.sigma <span class="ot">&lt;-</span> post2<span class="sc">$</span>sigma[ sample2.rows ]</span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>( sample2.mu , sample2.sigma , <span class="at">cex=</span><span class="fl">0.5</span> ,</span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a><span class="at">col=</span><span class="fu">col.alpha</span>(rangi2,<span class="fl">0.1</span>) ,</span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a><span class="at">xlab=</span><span class="st">"mu"</span> , <span class="at">ylab=</span><span class="st">"sigma"</span> , <span class="at">pch=</span><span class="dv">16</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Inspect the marginal posterior density for σ, averaging over µ, produced with:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>( sample2.sigma , <span class="at">norm.comp=</span><span class="cn">TRUE</span> )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.25-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>the posterior for σ is not Gaussian, but rather has a long tail of uncertainty towards higher values</li>
</ul>
</section>
<section id="finding-posterior-distribution-with-quap" class="level4">
<h4 class="anchored" data-anchor-id="finding-posterior-distribution-with-quap">Finding posterior distribution with <code>quap</code></h4>
<p><strong>Quadratic approximation</strong>: quickly make inferences about the shape of the posterior. The posterior’s peak → <em>maximum a posteriori</em> estimate (MAP) = useful image of posterior’s shape at this peak</p>
<p><code>quap</code> in <code>rethinking</code> - define the posterior probability at each combination of parameter values.</p>
<ul>
<li><p>Then climbs the posterior distribution and find the peak, its MAP.</p></li>
<li><p>Estimates the quadratic curvature at the MAP to produce an approximation of the posterior distribution.</p></li>
<li><p>Remember: This procedure is very similar to what many non-Bayesian procedures do, just without any priors.</p></li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rethinking) <span class="co"># repeat code to load data and select out adults</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(Howell1)</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> Howell1</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d[ d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span> , ]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Model definition</th>
<th>R code</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(h_{i} \sim {Normal}(µ,σ)\)</span></td>
<td>height ~ dnorm(mu, sigma)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(µ \sim{Normal}(178, 20)\)</span></td>
<td>mu ~ dnorm(178,20)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(σ \sim {Uniform}(0, 50)\)</span></td>
<td>sigma ~ dunif(0,50)</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>flist <span class="ot">&lt;-</span> <span class="fu">alist</span>(</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  mu <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>, <span class="dv">20</span>),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>,<span class="dv">50</span>)</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Fit model to the dataframe d2:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># fit model stored in m4.1</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(flist, <span class="at">data=</span>d2)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="co">#look at posterior distribution </span></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            mean        sd       5.5%      94.5%
mu    154.607238 0.4119931 153.948793 155.265682
sigma   7.731304 0.2913833   7.265617   8.196991</code></pre>
</div>
</div>
<p>These numbers provide Gaussian approximations for each parameter’s <em>marginal</em> distribution. This means the plausibility of each value of µ, after averaging over the plausibilities of each value of σ, is given by a Gaussian distribution with mean 154.6 and standard deviation 0.4.</p>
<p><strong>Start values for quap</strong> climbing a hill - needs to start at some combo of parameter values (usually random vals sampled from prior). Possible to specify starting val, like the mean and sd in this context.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>start <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">mu=</span><span class="fu">mean</span>(d2<span class="sc">$</span>height),</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">sigma=</span><span class="fu">sd</span>(d2<span class="sc">$</span>height)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(flist, <span class="at">data=</span>d2, <span class="at">start=</span>start)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Difference between <code>alist</code> and <code>list</code>: both make collections of arbitrary R objects</p>
<ul>
<li><p><code>list</code> evaluates the code embedded inside - use when defining list of start values</p></li>
<li><p><code>alist</code> does not execute code inside</p></li>
</ul>
<p>Using a more informative prior (mean of 0.1 = narrow prior). µ won’t change much, but the estimate for σ does</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    mu <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>,<span class="fl">0.1</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>,<span class="dv">50</span>)</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data =</span> d2</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           mean        sd      5.5%     94.5%
mu    177.86375 0.1002354 177.70356 178.02395
sigma  24.51756 0.9289233  23.03297  26.00216</code></pre>
</div>
</div>
<p>Sampling from quap.</p>
<ul>
<li><p>A quadratic approx to a posterior distribution with more than one parameter (e.g., µ and σ) is just a multi-dimensional Gaussian distribution</p></li>
<li><p>quap calculates deviations for all parameters and also <strong>covariances</strong> among pairs of parameters</p>
<ul>
<li>A list of means and a matrix of variances and covariances - sufficient to describe a multi-dimensional Gaussian distribution</li>
</ul></li>
</ul>
<p><strong>Variance-Covariance Matrix</strong>: shows how each parameter relates to every other parameter in the posterior distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vcov</span>(m4<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                mu        sigma
mu    0.1697383448 0.0002227304
sigma 0.0002227304 0.0849042197</code></pre>
</div>
</div>
<p>A variance-covariance matrix can be factored into two elements: (1) a vector of variances for the parameters and (2) a correlation matrix that tells us how changes in any parameter lead to correlated changes in the others.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diag</span>(<span class="fu">vcov</span>(m4<span class="fl">.1</span>)) <span class="co"># list of variances, if squared = the SDs in precis output </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mu      sigma 
0.16973834 0.08490422 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov2cor</span>(<span class="fu">vcov</span>(m4<span class="fl">.1</span>)) <span class="co"># correlation matrix </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>               mu       sigma
mu    1.000000000 0.001855346
sigma 0.001855346 1.000000000</code></pre>
</div>
</div>
<ul>
<li><p>List of variances: if squared, we get the SDs in the <code>precis</code> output</p></li>
<li><p>Correlation matrix: correlations are close to 0, so learning µ tells us little about σ and vice versa</p></li>
</ul>
<p><strong>Sample vectors of values from a multi-dimensional Gaussian distribution.</strong> <code>extract.samples()</code> from the <code>rethinking</code> package.</p>
<ul>
<li><code>extract.samples</code> uses <code>mvrnorm()</code> which is like <code>rnorm</code> but simulates random vectors of multivariate Gaussian values.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.1</span>, <span class="at">n=</span><span class="fl">1e4</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(post)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        mu    sigma
1 154.6597 7.707231
2 154.7070 7.814399
3 154.4769 7.524457
4 154.9464 7.557132
5 154.0725 7.744343
6 154.0847 8.409307</code></pre>
</div>
</div>
<p>You end up with a data frame, post, with 10,000 (1e4) rows and two columns, one column for µ and one for σ. Each value is a sample from the posterior</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(post)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            mean        sd       5.5%      94.5%      histogram
mu    154.606403 0.4117856 153.942190 155.268044        ▁▁▅▇▂▁▁
sigma   7.734802 0.2936643   7.263177   8.204982 ▁▁▁▁▁▂▅▇▇▃▁▁▁▁</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">"Vs m4.1 posterior"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Vs m4.1 posterior"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>            mean        sd       5.5%      94.5%
mu    154.607238 0.4119931 153.948793 155.265682
sigma   7.731304 0.2913833   7.265617   8.196991</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Compare o the grid approx</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(post)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="linear-prediction" class="level2">
<h2 class="anchored" data-anchor-id="linear-prediction">Linear Prediction</h2>
<p><strong>Predictor variable</strong>: independent variable we posit predicts the outcome if it has statistical association with the outcome variable.</p>
<p>How Kalahari height (outcome var) covaries with weight (predictor var). Seems dull now because readers don’t have a theory about growth and life history in mind.</p>
<p>Plot the height and weight against one another to get a sense of how they covary:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(d2<span class="sc">$</span>height, d2<span class="sc">$</span>weight)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>How to incorporate predictor vars into Gaussian model?</p>
<p><strong>The linear model strategy.</strong> Make the parameter for the mean of a Gaussian distribution µ ito a linear function of the predictor variable and other new parameters we invent.</p>
<ul>
<li>This instructs the golem to assume that the predictor variable has a constant and additive relationship to the mean of the outcome. It then computes the posterior distribution of this constant relationship</li>
</ul>
<div class="callout callout-style-simple callout-note no-icon">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-body-container">
<p>We ask the golem: “Consider all the lines that relate one variable to the other. Rank all of these lines by plausibility, given these data.”</p>
<p>The golem answers with a posterior distribution.</p>
</div>
</div>
</div>
<p>Case study: one predictor variable (weight). How to get weight into Gaussian model of height? Define µ as a function of values in x (<code>d2$weight</code>), with <span class="math inline">\(\overline{x}\)</span> as the average of weights.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 23%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(h_{i} \sim {Normal}(µ_{i},σ)\)</span></th>
<th>likelihood</th>
<th><code>height ~ dnorm(mu,sigma)</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(µ_{i} = \alpha + \beta(x_{i} - \overline x)\)</span></td>
<td><strong>linear model</strong></td>
<td><code>mu ← a + b*weight</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(\alpha \sim{Normal}(178, 20)\)</span></td>
<td><span class="math inline">\(\alpha\)</span> <strong>prior</strong></td>
<td><code>a ~ dnorm(178, 20)</code></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta \sim{Normal}(0,10)\)</span></td>
<td><span class="math inline">\(\beta\)</span> <strong>prior</strong></td>
<td><code>b ~ dlnorm(0,1)</code></td>
</tr>
<tr class="even">
<td><span class="math inline">\(σ \sim {Uniform}(0, 50)\)</span></td>
<td><span class="math inline">\(\sigma\)</span> <strong>prior</strong></td>
<td><code>sigma ~ dunif(0,50)</code></td>
</tr>
</tbody>
</table>
<section id="probability-of-the-data" class="level4">
<h4 class="anchored" data-anchor-id="probability-of-the-data">Probability of the data</h4>
<p>Probability of the observed height. The mean µ noe depends on unique values on each row i.</p>
</section>
<section id="linear-model" class="level4">
<h4 class="anchored" data-anchor-id="linear-model">Linear Model</h4>
<p>The mean µ is not longer a parameter to be estimated, instead <span class="math inline">\(µ_{i}\)</span> is determined by other parameters <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta\)</span>, and the observed variable <span class="math inline">\(x\)</span>. We know <span class="math inline">\(µ_{i}\)</span> with certainty (not stochastic). <span class="math inline">\(x_{i}\)</span> is weight value on row <span class="math inline">\(i\)</span>.</p>
<p>Asks two questions:</p>
<ol type="1">
<li>What is the expected height when <span class="math inline">\(x_{i} = \overline{x}\)</span> ? <span class="math inline">\(µ_{i} = \alpha\)</span> when <span class="math inline">\(x_{i} = \overline{x}\)</span>.</li>
<li>What is the change in expected height when <span class="math inline">\(x_{i}\)</span> changes by 1 unit? <span class="math inline">\(\beta\)</span> is the slope - rate of change in expectation</li>
</ol>
<p>Find the line that relates <span class="math inline">\(x\)</span> to <span class="math inline">\(h\)</span> - a line that passes through <span class="math inline">\(\alpha\)</span> when <span class="math inline">\(x_{i} = \overline{x}\)</span> and has slope <span class="math inline">\(\beta\)</span></p>
</section>
<section id="remaining-priors" class="level4">
<h4 class="anchored" data-anchor-id="remaining-priors">Remaining priors</h4>
<p>These last priors define distributions for the unobserved variables.</p>
<p><span class="math inline">\(\beta\)</span> prior: why Gaussian prior with mean 0?</p>
<p>Simulate a hundred pairs of alpha and beta:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2971</span>) </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span>      <span class="co">#100 lines</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N,<span class="dv">178</span>,<span class="dv">20</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N,<span class="dv">0</span>,<span class="dv">10</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now plot the lines:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>,<span class="at">xlim=</span><span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>,<span class="dv">400</span>), <span class="at">xlab=</span><span class="st">"weight"</span>, <span class="at">ylab=</span><span class="st">"height"</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>) <span class="co"># no one is negative height</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">272</span>, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">lwd=</span><span class="fl">0.5</span>) <span class="co"># tallest person </span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">"b ~ dnorm(0,10"</span>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(d2<span class="sc">$</span>weight) </span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) <span class="fu">curve</span>(a[i] <span class="sc">+</span> b[i] <span class="sc">*</span>(x<span class="sc">-</span>xbar),<span class="at">from =</span> <span class="fu">min</span>(d2<span class="sc">$</span>weight),<span class="at">to=</span><span class="fu">max</span>(d2<span class="sc">$</span>weight), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="fu">col.alpha</span>(<span class="st">"black"</span>, <span class="fl">0.2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Relationship between weight and height can be absurdly positive or negative</p></li>
<li><p>Know that height INC with avg weight. Restrict to positive values → define prior as <span class="math inline">\(\beta \sim{Log-Normal}(0,1)\)</span>. Log of <span class="math inline">\(\beta\)</span> has a Normal(0,1) distribution</p></li>
</ul>
<p><code>dlnorm</code> and <code>rlnorm</code> densities for working with log-normal distributions</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(<span class="fl">1e4</span>, <span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(b, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">5</span>), <span class="at">adj=</span><span class="fl">0.1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>If log of beta is normal, then beta itself is strictly positive</li>
</ul>
<p>Re-doing the prior predictive simulation with Log-Normal</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2971</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span> </span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(N, <span class="dv">178</span>,<span class="dv">20</span>)</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>b <span class="ot">&lt;-</span> <span class="fu">rlnorm</span>(N,<span class="dv">0</span>,<span class="dv">1</span>)</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="co"># plotting</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="cn">NULL</span>,<span class="at">xlim=</span><span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">100</span>,<span class="dv">400</span>), <span class="at">xlab=</span><span class="st">"weight"</span>, <span class="at">ylab=</span><span class="st">"height"</span>)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">0</span>, <span class="at">lty=</span><span class="dv">2</span>) <span class="co"># no one is negative height</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">272</span>, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">lwd=</span><span class="fl">0.5</span>) <span class="co"># tallest person </span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="st">"log(b) ~ dnorm(0,1)"</span>)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(d2<span class="sc">$</span>weight) </span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) <span class="fu">curve</span>(a[i] <span class="sc">+</span> b[i] <span class="sc">*</span>(x<span class="sc">-</span>xbar),<span class="at">from =</span> <span class="fu">min</span>(d2<span class="sc">$</span>weight),<span class="at">to=</span><span class="fu">max</span>(d2<span class="sc">$</span>weight), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="fu">col.alpha</span>(<span class="st">"black"</span>, <span class="fl">0.2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Now all lines in the joint prior for alpha and beta are within human reason</li>
</ul>
<p>Important to fuss over priors (even if they end up being irrelevant due to big data). Because some priors may end up being relevant for many other analyses and it helps us build better models.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Choosing priors
</div>
</div>
<div class="callout-body-container callout-body">
<p>Priors encode states of info before seeing the data.</p>
<ul>
<li><p>In cases with good prior info that discounts the plausibility of some parameter values (e.g., neg associations between height and weight) - encode directly in priors</p></li>
<li><p>Vary priors and repeat the analysis in order to study how different states of initial info influence inference</p></li>
<li><p>Often, many reasonable priors produce same inference</p></li>
<li><p>Conventional Bayesian priors are <em>conservative</em> relative to conventional non-Bayesian approaches</p></li>
<li><p>Choose priors conditional on <strong>pre-data knowledge of the data (constraints, ranges, theoretical relationships</strong>) never conditional on the observed sample</p></li>
</ul>
</div>
</div>
</section>
<section id="finding-the-posterior-distribution" class="level4">
<h4 class="anchored" data-anchor-id="finding-the-posterior-distribution">Finding the posterior distribution</h4>
<p>Just incorporate new model of the mean into the model specification inside <code>quap</code> and make sure to add a prior for the new parameter <span class="math inline">\(\beta\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load data again, since it's a long way back </span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rethinking)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"Howell1"</span>)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> Howell1</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>d2 <span class="ot">&lt;-</span> d[d<span class="sc">$</span>age <span class="sc">&gt;=</span> <span class="dv">18</span>,]</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="co"># define the average weight, x-bar </span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(d2<span class="sc">$</span>weight)</span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a><span class="co">#fit model </span></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>m4<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b<span class="sc">*</span>(weight <span class="sc">-</span> xbar),</span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>,<span class="dv">20</span>),</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a>    b <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>,<span class="dv">50</span>)</span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>  ),</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">data=</span>d2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="interpreting-the-posterior-distribution" class="level4">
<h4 class="anchored" data-anchor-id="interpreting-the-posterior-distribution">Interpreting the posterior distribution</h4>
<p><strong>Tables of marginal distributions</strong>: inspect the marginal posterior distributions of the parameters</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">precis</span>(m4<span class="fl">.3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             mean         sd        5.5%       94.5%
a     154.6013671 0.27030766 154.1693633 155.0333710
b       0.9032807 0.04192363   0.8362787   0.9702828
sigma   5.0718809 0.19115478   4.7663786   5.3773831</code></pre>
</div>
</div>
<p><u>Focus on new parameter <span class="math inline">\(\beta\)</span></u>. Mean on 0.9 = <em>a person 1kg heavier is expected to by 0.90 cm taller</em>. 89% of the posterior probability lies between 0.84 and 0.97. <span class="math inline">\(\beta\)</span> vals close to 0 or greatly above 1 are highly incompatible with these data and this model.</p>
<ul>
<li>Not suggesting that the relationship between height and weight are linear, just that: if you’re committed to a line, then lines with slope <code>0.9</code> are plausible ones</li>
</ul>
<p>Also need variance-covariance matrix to describe the quadratic posterior completely, along with <code>precis()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">vcov</span>(m4<span class="fl">.3</span>), <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>          a     b sigma
a     0.073 0.000 0.000
b     0.000 0.002 0.000
sigma 0.000 0.000 0.037</code></pre>
</div>
</div>
<p>Very little covariation among the parameters.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(m4<span class="fl">.3</span>) <span class="co">#shows both marginal posteriors and covariance </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in par(usr): argument 1 does not name a graphical parameter
Warning in par(usr): argument 1 does not name a graphical parameter
Warning in par(usr): argument 1 does not name a graphical parameter</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Plotting posterior inference against the data.</strong></p>
<p>Plot raw data, compute posterior mean values for a and b, draws implied line.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, <span class="at">data=</span>d2, <span class="at">col=</span>rangi2)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.3</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>a_map <span class="ot">&lt;-</span> <span class="fu">mean</span>(post<span class="sc">$</span>a)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>b_map <span class="ot">&lt;-</span> <span class="fu">mean</span>(post<span class="sc">$</span>b)</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(a_map <span class="sc">+</span> b_map <span class="sc">*</span> (x <span class="sc">-</span> xbar), <span class="at">add=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.46-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Each point in this plot is a single individual. The black line (posterior mean) is defined by the mean slope β and mean intercept α. This is not a bad line. But lots of other highly plausible lines near it.</p>
<p><strong>Adding uncertainty around the mean</strong>.</p>
<p>Each combo of <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(\beta\)</span> has posterior probability. How to get uncertainty into the plot: sample a bunch of lines from the posterior distribution, display lines on plot to visualize the uncertainty in the regression relationship</p>
<p>Work with all the samples from the model</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.3</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>post[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         a         b    sigma
1 154.5789 0.9376825 5.220756
2 154.4067 0.8937310 4.752735
3 154.4622 0.9150822 5.341227
4 154.2649 0.9236067 5.160423
5 155.1258 0.9495934 5.108891</code></pre>
</div>
</div>
<ul>
<li><p>each row is a correlated random sample from the joint posterior of all three parameters, using the covariances provided by <code>vcov(m4.3)</code></p>
<ul>
<li><p>The average of very many of these lines = <strong>posterior mean line</strong></p></li>
<li><p>Scatter around the average alters our confidence in the relationship between the predictor and outcome</p></li>
</ul></li>
</ul>
<p>Display bunch of the lines incrementally - see scatter</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">100</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>dN <span class="ot">&lt;-</span> d2[<span class="dv">1</span><span class="sc">:</span>N,]</span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>mN <span class="ot">&lt;-</span> <span class="fu">quap</span>(</span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">alist</span>(</span>
<span id="cb71-5"><a href="#cb71-5" aria-hidden="true" tabindex="-1"></a>    height <span class="sc">~</span> <span class="fu">dnorm</span>(mu, sigma),</span>
<span id="cb71-6"><a href="#cb71-6" aria-hidden="true" tabindex="-1"></a>    mu <span class="ot">&lt;-</span> a <span class="sc">+</span> b<span class="sc">*</span>(weight <span class="sc">-</span> <span class="fu">mean</span>(weight)),</span>
<span id="cb71-7"><a href="#cb71-7" aria-hidden="true" tabindex="-1"></a>    a <span class="sc">~</span> <span class="fu">dnorm</span>(<span class="dv">178</span>,<span class="dv">20</span>),</span>
<span id="cb71-8"><a href="#cb71-8" aria-hidden="true" tabindex="-1"></a>    b <span class="sc">~</span> <span class="fu">dlnorm</span>(<span class="dv">0</span>,<span class="dv">1</span>),</span>
<span id="cb71-9"><a href="#cb71-9" aria-hidden="true" tabindex="-1"></a>    sigma <span class="sc">~</span> <span class="fu">dunif</span>(<span class="dv">0</span>,<span class="dv">50</span>)</span>
<span id="cb71-10"><a href="#cb71-10" aria-hidden="true" tabindex="-1"></a>  ), <span class="at">data=</span>dN</span>
<span id="cb71-11"><a href="#cb71-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb71-12"><a href="#cb71-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-13"><a href="#cb71-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract 20 samples from the posterior </span></span>
<span id="cb71-14"><a href="#cb71-14" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(mN, <span class="at">n=</span><span class="dv">20</span>)</span>
<span id="cb71-15"><a href="#cb71-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-16"><a href="#cb71-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Display raw data and sample size </span></span>
<span id="cb71-17"><a href="#cb71-17" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dN<span class="sc">$</span>weight, dN<span class="sc">$</span>height, </span>
<span id="cb71-18"><a href="#cb71-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlim=</span><span class="fu">range</span>(d2<span class="sc">$</span>weight), <span class="at">ylim=</span><span class="fu">range</span>(d2<span class="sc">$</span>height),</span>
<span id="cb71-19"><a href="#cb71-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span>rangi2, <span class="at">xlab=</span><span class="st">"weight"</span>, <span class="at">ylab=</span><span class="st">"height"</span>)</span>
<span id="cb71-20"><a href="#cb71-20" aria-hidden="true" tabindex="-1"></a><span class="fu">mtext</span>(<span class="fu">concat</span>(<span class="st">"N = "</span>, N))</span>
<span id="cb71-21"><a href="#cb71-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-22"><a href="#cb71-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the lines, with transparency </span></span>
<span id="cb71-23"><a href="#cb71-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>)</span>
<span id="cb71-24"><a href="#cb71-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">curve</span>(post<span class="sc">$</span>a[i] <span class="sc">+</span> post<span class="sc">$</span>b[i]<span class="sc">*</span>(x <span class="sc">-</span> <span class="fu">mean</span>(dN<span class="sc">$</span>weight)),</span>
<span id="cb71-25"><a href="#cb71-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="fu">col.alpha</span>(<span class="st">"black"</span>, <span class="fl">0.3</span>), <span class="at">add=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.48-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li>Notice that the cloud of regression lines becomes more compact as the sample size (N) increases. Model grows more confident about location of mean</li>
</ul>
<p><strong>Plotting regression intervals and contours</strong>: More informative to see uncertainty by plotting an interval or contour around the average regression line.</p>
<p>Make list of 10,000 vals of µ for an individual who weights 50kg (<span class="math inline">\(x_{i}\)</span>) via samples from posterior</p>
<p><span class="math display">\[
µ_{i} = \alpha + \beta(x_{i}-\overline{x})
\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>post <span class="ot">&lt;-</span> <span class="fu">extract.samples</span>(m4<span class="fl">.3</span>)</span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>mu_at_50 <span class="ot">&lt;-</span> post<span class="sc">$</span>a <span class="sc">+</span> post<span class="sc">$</span>b <span class="sc">*</span> (<span class="dv">50</span> <span class="sc">-</span> xbar)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting mu_at_50 = Vector of predicted means, one for each random sample from the posterior </span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a><span class="fu">dens</span>(mu_at_50, <span class="at">col=</span>rangi2, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">xlab=</span><span class="st">"mu|weight=50"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.50-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Since the components of µ have distributions, so too does µ. And since the distributions of α and β are Gaussian, so to is the distribution of µ (adding Gaussian distributions always produces a Gaussian distribution).</p>
<p>Since the posterior for µ is a distribution, you can find intervals for it, just like for any posterior distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">PI</span>(mu_at_50, <span class="at">prob=</span><span class="fl">0.89</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      5%      94% 
158.5785 159.6799 </code></pre>
</div>
</div>
<ul>
<li>the central 89% of the ways for the model to produce the data place the average height between about 159 cm and 160 cm (conditional on the model and data), assuming the weight is 50 kg.</li>
</ul>
<p>That’s good so far, but we need to repeat the above calculation for every weight value on the horizontal axis, not just when it is 50 kg. Use the <code>link</code> function from <code>rethinking</code>. It takes the <code>quap</code> approx, samples from the posterior distribution, and computes µ for each case in the data and sample from the post distribution.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.3</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mu)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:1000, 1:352] 158 157 157 157 157 ...</code></pre>
</div>
</div>
<ul>
<li><p>Output: big matrix of µ values</p>
<ul>
<li><p>Each row = sample from post distri (default = 1000 samples)</p></li>
<li><p>Each column = case in the data (352 columns in this matrix)</p></li>
</ul></li>
<li><p>This is a distribution of µ for each individual in the original data</p></li>
</ul>
<p>Now, let’s get a distribution of µ for each unique weight value on the horizationtal axis:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define sequence of wights to compute predictions for </span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="co"># these values will be on the horiz axis</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>weight.seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">25</span>, <span class="dv">70</span>, <span class="at">by=</span><span class="dv">1</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Use link() to compute mu </span></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a><span class="co"># For each sample from posterior </span></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="co"># and for each weight in weight.seq</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>mu <span class="ot">&lt;-</span> <span class="fu">link</span>(m4<span class="fl">.3</span>, <span class="at">data=</span><span class="fu">data.frame</span>(<span class="at">weight=</span>weight.seq))</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(mu)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:1000, 1:46] 136 136 136 137 137 ...</code></pre>
</div>
</div>
<ul>
<li>Now only 46 columns in <code>mu</code> - fed it 46 diff values for <code>weight</code></li>
</ul>
<p>Visualize by plotting the distribution of µ values at each height</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use type="n" to hide raw data </span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, d2, <span class="at">type=</span><span class="st">"n"</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Loop over samples and plot each mu value </span></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>)</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">points</span>(weight.seq, mu[i,], <span class="at">pch=</span><span class="dv">16</span>, <span class="at">col=</span><span class="fu">col.alpha</span>(rangi2,<span class="fl">0.1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.55-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>At each weight value in <code>weight.seq</code>, a pile of computed µ values are shown. Each of the piles is a Gaussian distribution</p>
<ul>
<li>The amount of uncertainty in µ depends on the value of <code>weight</code></li>
</ul></li>
</ul>
<p>Summarize the distribution for each weight value, using <code>apply()</code></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarize the distribution of mu </span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute the mean of each column (dimension "2") of the matrix mu </span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>mu.mean <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, mean)   <span class="co">#contains the average mu at each weight value</span></span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Compute the PI (89% interval) of each column of the matrix mu </span></span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a>mu.PI <span class="ot">&lt;-</span> <span class="fu">apply</span>(mu, <span class="dv">2</span>, PI, <span class="at">prob=</span><span class="fl">0.89</span>)   <span class="co">#contains 89% lower and upper bounds for each weight value </span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plot these summaries on top of the data</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#plot raw data </span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="co"># fading out points to make line and interval more visible </span></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(height <span class="sc">~</span> weight, <span class="at">data=</span>d2, <span class="at">col=</span><span class="fu">col.alpha</span>(rangi2,<span class="fl">0.5</span>))</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the MAP line, aka the mu for each weight </span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(weight.seq, mu.mean)</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the shaded region for 89% PI </span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a><span class="fu">shade</span>(mu.PI, weight.seq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="SR_Ch04_notes_files/figure-html/4.57-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Using this approach, can derive and plot the posterior prediction means and intervals for quite complicated models, for any data you choose.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Recipe for generating predictions and intervals from the posterior of a fit model
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>Use <code>link</code> to generate distributions of posterior values for µ. The default behavior of <code>link</code> is to use the original data, so you have to pass it a list of new horiz axis values you want to plot posterior predictions across</li>
<li>Use summary functions like <code>mean</code> or <code>PI</code> to find averages and lower and upper bounds of µ for each value of the predictor variable</li>
<li>Finally, use plotting functions like <code>lines</code> or <code>shade</code> to draw the lines and intervals. Or you might plot the distributions of the predictions, or do further numerical calculations with them</li>
</ol>
<p>Recipe words for every model we fit in the book. As long as you know how parameters relate to the data, you can use samples from the posterior to describe any aspect of the model’s behavior.</p>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>